language: php
dist: precise
sudo: false

php:
  - 5.3
  - 5.6
  - 7.0

env:
  - WP_VERSION=latest
  - WP_VERSION=4.3
  - WP_VERSION=4.2

matrix:
  exclude:
    - env: WP_VERSION=4.2

before_script:
  - bash tests/install.sh $WP_VERSION
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      if [[ ${TRAVIS_PHP_VERSION:0:2} == "5." ]]; then
        composer global require "phpunit/phpunit=4.8.*"
      else
        composer global require "phpunit/phpunit=5.7.*"
      fi
    fi

script: phpunit
