language: php
dist: precise
sudo: false

php:
  - 5.6
  - 7.0

env:
  - WP_VERSION=latest
  - WP_VERSION=4.8

before_script:
  - bash tests/install.sh $WP_VERSION
  - composer global require "phpunit/phpunit=5.*"

script: phpunit
