language: php
sudo: false

php:
  - 5.3
  - 5.6
  - 7.0

env:
  - WP_VERSION=latest
  - WP_VERSION=4.3
  - WP_VERSION=4.2

matrix:
  exclude:
    - php: 7.0
      env: WP_VERSION=4.2

before_script:
  - bash tests/install.sh $WP_VERSION

script: phpunit
