language: php
sudo: false

php:
  - 5.3
  - 5.4

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=4.2 WP_MULTISITE=0
  - WP_VERSION=4.2 WP_MULTISITE=1

before_script:
  - bash tests/install.sh $WP_VERSION

script: phpunit
